server.port: 8081

spring:
  config:
    import: optional:file:env.properties
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  mvc:
    pathmatch:
      matchingStrategy: ant-path-matcher
    throwExceptionIfNoHandlerFound: true
  web:
    resources:
      addMappings: false
  messages:
    basename: messages

server:
  error:
    includeMessage: always
    includeBindingErrors: always

logging:
  level:
    org:
      hibernate:
        type: trace